### ISSUE TITLE
Broken Routes

### ISSUE THREAD

**Issue by johntom** [pixelmund/full-stack-svelte-kit-example#2]
1) The install now works.
2) Create User works
3) Add New/Edit  Post works
4) Login fails after a logout
5) Routing  back from either place raises

500
Failed to fetch
TypeError: Failed to fetch
    at Renderer._load (http://localhost:3000/@fs/devel/Svelte/svemix-example/.svelte-kit/runtime/client/start.js:1269:25)
    at async Renderer._get_navigation_result (http://localhost:3000/@fs/devel/Svelte/svemix-example/.svelte-kit/runtime/client/start.js:999:19)
    at async Renderer.update (http://localhost:3000/@fs/devel/Svelte/svemix-example/.svelte-kit/runtime/client/start.js:831:27)
    at async Renderer.handle_navigation (http://localhost:3000/@fs/devel/Svelte/svemix-example/.svelte-kit/runtime/client/start.js:820:3)
    at async Router._n
    
All things consirdered, it looks very promising.

**Comment by pixelmund** [comment]
There is an open issue on the sveltekit repo: [https://github.com/sveltejs/kit/issues/3718](https://github.com/sveltejs/kit/issues/3718)

**Comment by johntom** [comment]
Yep, quick workaround is manually edit the node_modules/@sveltejs/kit/assets/client/start.js~1269:

const res = await fetch(`${url.pathname == '/' ? '' : url.pathname}/__data.json`, {
